---
title: "Untitled"
output: html_document
date: '2022-04-28'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=TRUE, message=FALSE, warning=FALSE}
# Load required packages -------------------------------------------------------  
if (!require("pacman")) install.packages("pacman")
pacman::p_load(here,
               janitor,
               rsdmx,
               clock,
               tidyverse,
               palmerpenguins)  
```


# {.tabset}

```{r, echo=TRUE, results='hide'}
# Create a list of plots -------------------------------------------------------
plot_bill_length_vs_depth <- function(penguin_species) {
  palmerpenguins::penguins %>%
    filter(species == penguin_species) %>%
    ggplot(aes(x = bill_length_mm,
               y = bill_depth_mm)) +
    geom_point() + 
    labs(title = paste0("Species: ", penguin_species)) +  
    theme_bw() +
    theme(panel.grid = element_line(linetype = "dotted"))
}

# Extract distinct species names and create a plot per species  
plots <- palmerpenguins::penguins %>%
  distinct(species) %>%
  pull(species) %>%
  map(~ plot_bill_length_vs_depth(.x)) 

# Set plot names  
species_names <- palmerpenguins::penguins %>%
  distinct(species) %>%
  pull(species) 

plots <- set_names(plots, species_names)
```

```{r, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}
# Use a for loop to print code for tab creation via R Markdown -----------------  
# Set echo=FALSE and results='asis' in code chunk  
# Insert chunk between a header labelled `{.tabset}` and a header labelled `{-}`  
# store plot as temp object and then print temp object

for (i in seq_along(plots)) {
  temp <- plots[[i]]
  cat("##", "Species: ", names(plots[i]), "\n") # Create tabs from plot names
  print(temp) 
  cat("\n\n")
}
```

# {-}